/*
 Copyright 2016 Goldman Sachs.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
 */

/* Generated By:JJTree: Do not edit this line. ASTequalsEdgePointClause.java */


package com.gs.fw.common.mithra.generator.queryparser;

import com.gs.fw.common.mithra.generator.MithraObjectTypeWrapper;

public class ASTequalsEdgePointClause extends SimpleNode implements Operator
{

    public ASTequalsEdgePointClause(int id)
    {
        super(id);
    }

    public ASTequalsEdgePointClause(MithraQL p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(MithraQLVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public boolean involvesThis()
    {
        return getAttribute().belongsToThis();
    }

    private ASTAttributeName getAttribute()
    {
        return ((ASTRelationalExpression) this.parent).getLeft();
    }

    public boolean involvesClassAsNonThis(MithraObjectTypeWrapper owner)
    {
        return !this.involvesThis() && this.getAttribute().getOwner().equals(owner);
    }

    public boolean involvesOnlyThis(MithraObjectTypeWrapper mithraObjectTypeWrapper)
    {
        return this.involvesClassAsNonThis(mithraObjectTypeWrapper);
    }

    public boolean isGreaterThan()
    {
        return false;
    }

    public boolean isLesserThan()
    {
        return false;
    }

    public boolean isGreaterThanOrEqualTo()
    {
        return false;
    }

    public boolean isLesserThanOrEqualTo()
    {
        return false;
    }

    public boolean isEqual()
    {
        return false;
    }

    public boolean isNotEqual()
    {
        return false;
    }

    public boolean isIn()
    {
        return false;
    }

    public Operator getReverseOperator()
    {
        throw new RuntimeException("not implemented");
    }

    public String getMethodName()
    {
        return "equalsEdgePoint";
    }

    public boolean isIsNullOrIsNotNull()
    {
        return false;
    }

    @Override
    public boolean isIsNotNull()
    {
        return false;
    }

    public boolean isUnary()
    {
        return true;
    }

    public boolean isEqualsEdgePoint()
    {
        return true;
    }

    public String getPrimitiveExpression(String left, String right)
    {
        throw new RuntimeException("not implemented");
    }

    public String getNonPrimitiveExpression(String left, String right)
    {
        return "true";
    }

    public String toString()
    {
        return this.getMethodName();
    }

    public boolean equalsOther(SimpleNode other)
    {
        return other instanceof ASTequalsEdgePointClause;
    }
}
