/*
 Copyright 2016 Goldman Sachs.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
 */

/* Generated By:JJTree: Do not edit this line. C:/users/projects/PARA4.0/src/com/gs/fw/common/mithra/generator/queryparser\MithraQLTreeConstants.java */

package com.gs.fw.common.mithra.generator.queryparser;

public interface MithraQLTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTATTRIBUTENAME = 1;
  public int JJTRELATIONALOPERATOR = 2;
  public int JJTINOPERATOR = 3;
  public int JJTVOID = 4;
  public int JJTOREXPRESSION = 5;
  public int JJTANDEXPRESSION = 6;
  public int JJTRELATIONALEXPRESSION = 7;
  public int JJTISNULLCLAUSE = 8;
  public int JJTEQUALSEDGEPOINTCLAUSE = 9;
  public int JJTLITERAL = 10;
  public int JJTINLITERAL = 11;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "AttributeName",
    "RelationalOperator",
    "InOperator",
    "void",
    "OrExpression",
    "AndExpression",
    "RelationalExpression",
    "IsNullClause",
    "equalsEdgePointClause",
    "Literal",
    "InLiteral",
  };
}
